airbnb/epoxy-ios

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/ItemPath.swift
Sources/EpoxyCollectionView/Models/ItemModel/ItemCellMetadata.swift
Sources/EpoxyCore/Model/Providers/ViewDifferentiatorProviding.swift

There's not a good reason to keep these as `let`s, as these types have public memberwise `init`s and these properties don't need to be kept in sync.

Update public struct properties to be var

---

CHANGELOG.md
Example/EpoxyExample.xcodeproj/project.pbxproj
Example/EpoxyExample/ViewControllers/CardStackViewController.swift
Example/EpoxyExample/ViewControllers/CompositionalLayoutViewController.swift
Example/EpoxyExample/ViewControllers/MainViewController.swift
Example/EpoxyExample/Views/CardContainer.swift
Sources/EpoxyBars/BarInstaller/BarContainer.swift
Sources/EpoxyBars/BarInstaller/BarInstaller.swift
Sources/EpoxyBars/BarInstaller/BarStackView.swift
Sources/EpoxyBars/BarInstaller/BarWrapperView.swift
Sources/EpoxyBars/BottomBarInstaller/BottomBarContainer.swift
Sources/EpoxyBars/Keyboard/InputAccessoryBarStackView.swift
Sources/EpoxyBars/TopBarInstaller/TopBarContainer.swift

- Remove the style, instead favoring public vars and content properties for settable properties
- Add an example that uses a BarStackView in a CollectionView within a CardContainer

Improve BarStackView APIs

---

README.md

We don't want this badge to be for all CI checks, which would make it failing more often than we'd like

Update build status badge to only be for CI on master branch

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/CollectionViewConfiguration.swift

We've verified that the primary issues with this behavior are no longer affecting newer iOS versions.

Enable CollectionView prefetching by default

---

CHANGELOG.md
Sources/EpoxyBars/BarInstaller/BarStackView.swift

If we call `insertArrangedSubview(_:at:)` as part of an animation transaction on an arranged subview, it will be moved with an animation. As such, we adopt this behavior in `BarStackView` to better respect the intent of the `animated` parameter to `setModels(_:animated:)`.

Support animated moves in bar stacks

---

CHANGELOG.md
Sources/EpoxyBars/BarCoordinator/CoordinatedBarModel.swift
Sources/EpoxyBars/BarInstaller/BarWrapperView.swift
Sources/EpoxyBars/BarModel/BarModel.swift
Sources/EpoxyBars/BarModel/InternalBarModeling.swift

If two bar views are of the same type but have different style IDs, we should just crossfade between them, rather than treating them as a delete and insert. As such, we remove the `styleID` from the `DiffIdentifier` and check it in `BarWrapperView` instead.

Crossfade between bars of the same view type with different style IDs

---

CHANGELOG.md
Example/EpoxyExample/ViewControllers/Readme/BottomButtonViewController.swift
Example/EpoxyExample/ViewControllers/Readme/CounterViewController.swift
Example/EpoxyExample/ViewControllers/Readme/FormNavigationController.swift
Example/EpoxyExample/ViewControllers/Readme/PresentationViewController.swift
Example/EpoxyExample/ViewControllers/Readme/ReadmeExamplesViewController.swift
README.md
Sources/EpoxyBars/BarModel/BarModelBuilder.swift
Sources/EpoxyBars/BottomBarInstaller/BottomBarInstaller.swift
Sources/EpoxyBars/Keyboard/InputAccessoryBarStackView.swift
Sources/EpoxyBars/TopBarInstaller/TopBarInstaller.swift
Sources/EpoxyCollectionView/Models/ItemModel/ItemModelBuilder.swift
Sources/EpoxyCollectionView/Models/SectionModel/SectionModel.swift
Sources/EpoxyCollectionView/Models/SectionModel/SectionModelBuilder.swift
Sources/EpoxyCollectionView/ViewControllers/CollectionViewController.swift
Sources/EpoxyCore/Model/EpoxyModelArrayBuilder.swift
Sources/EpoxyNavigationController/NavigationController.swift
Sources/EpoxyNavigationController/NavigationModelBuilder.swift
Sources/EpoxyPresentations/PresentationModelBuilder.swift
Tests/EpoxyTests/CoreTests/EpoxyModelBuilderArraySpec.swift
Tests/EpoxyTests/PresentationsTests/PresentationModelBuilderSpec.swift

This gives us a syntax that's much closer to SwiftUI, while still keeping the method signatures across the board.
I'll update all of the examples to use this new syntax in a follow up, since some of the new features require Swift 5.4.
```swift
@SectionModelBuilder private var sections: [SectionModel] {
SectionModel {
TextRow.itemModel(
dataID: DataID.row,
content: .init(
title: "Count \(count)",
body: "Tap to increment"),
style: .large)
.didSelect { [weak self] _ in
self?.count += 1
}
}
```

Add result builders for SectionModels, ItemModels, BarModels, PresentationModels, and NavigationModels

---

CHANGELOG.md
Sources/EpoxyCore/Model/EpoxyModelArrayBuilder.swift
Tests/EpoxyTests/CoreTests/EpoxyModelBuilderArraySpec.swift

This ensures that we can include both arrays and optional models in result builders. Without these changes, they result in a syntax error.

Add support for Array and Optional expressions to model result builders

---

CHANGELOG.md
Sources/EpoxyPresentations/PresentationModelBuilder.swift
Tests/EpoxyTests/PresentationsTests/PresentationModelBuilderSpec.swift

This change allows you to extract out a presentation method into a local computed property.

Add support for Optional expressions to PresentationModel result builders

---

CHANGELOG.md
Sources/EpoxyCollectionView/Models/ItemModel/AnyItemModel.swift
Sources/EpoxyCollectionView/Models/SupplementaryItemModel/AnySupplementaryItemModel.swift
Tests/EpoxyTests/CollectionViewTests/CollectionViewSpec.swift

Adding `SetContentProviding` to `AnyItemModel` to enable use of `adaptiveMarginsOverride` within `AnyItemModel`

Adding SetContentProviding to AnyItemModel

---

CHANGELOG.md
Sources/EpoxyBars/Keyboard/KeyboardPositionWatcher.swift

Adds a `keyboardContentInsetAdjustment` property to `UIScrollView` with the amount that the that its `contentInset.bottom` has been adjusted to accommodate for the keyboard by a `KeyboardPositionWatcher`.

Expose keyboardContentInsetAdjustment on UIScrollView

---

CHANGELOG.md
Sources/EpoxyBars/BarInstaller/BarInstaller.swift

Ensures that redundant calls to `install` or `uninstall` after either has occurred don't have extra side-effects.

Gracefully handle redundant calls to install/uninstall

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/ReusableViews/ItemSelectionStyle.swift

This makes it easier to make a selection style part of a style.
N/A, conformance is synthesized

Make ItemSelectionStyle conform to Hashable

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/Internal/CollectionViewDataSource.swift
Sources/EpoxyCollectionView/CollectionView/Internal/ReuseIDStore.swift
Sources/EpoxyCore/Model/Providers/ViewDifferentiatorProviding.swift
Tests/EpoxyTests/CollectionViewTests/ReuseIDStoreTests.swift

Currently, if a `styleID` is mutated after it is set on a collection view, it may result in a crash since we'll be attempting to dequeue a cell that wasn't registered. As such, we do two things to attempt to handle this gracefully:
- We assert in the `ReuseIDStore` in a new dequeue method, and then return a fallback reuse ID of the same component.
- Otherwise, we return an empty `UICollectionViewCell()`.

Gracefully handle styleID mutations after registration

---

CHANGELOG.md
Sources/EpoxyBars/BarModel/AnyBarModel.swift
Sources/EpoxyCollectionView/Models/ItemModel/AnyItemModel.swift
Sources/EpoxyCollectionView/Models/SupplementaryItemModel/AnySupplementaryItemModel.swift

As titled. This allows us to write more generic code on these type-erased models.

Make model type erasers conform to StyleIDProviding

---

CHANGELOG.md
Example/EpoxyExample.xcodeproj/project.pbxproj
Example/EpoxyExample/Data/Example.swift
Example/EpoxyExample/ViewControllers/MainViewController.swift
Example/EpoxyExample/ViewControllers/TextFieldViewController.swift
Example/EpoxyExample/Views/TextFieldRow.swift
README.md

👋 Airbnb Team, I added case with text field, I would like to show how can we use `avoidsKeyboard` feature, I did not find it in examples.
Main | Base | Keyboard
------- | ------- | -------

Add case with TextField

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/CollectionView.swift
Sources/EpoxyCollectionView/CollectionView/Internal/CollectionViewDataSource.swift

Allow specifying that `CollectionView`s should update using non-animated `performBatchUpdates(…)`, which can be more performant and behave more predictably than `reloadData()`.

Add update strategy to CollectionView

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/CollectionView.swift

When `bounds.size` is `.zero`, there's no benefit to doing batch updates.

Improve CollectionView logic for reload data override

---

CHANGELOG.md
Sources/EpoxyLayoutGroups/Groups/HGroup.swift

This adds `reflowsForAccessibilityTypeSizes` to `HGroup.Style` to make it easier to set, and to make it possible to set when using `HGroupView` directly.
@erichoracek

Add reflowsForAccessibilityTypeSizes to HGroup.Style

---

CHANGELOG.md
Sources/EpoxyLayoutGroups/Constrainable/ConstrainableContainer.swift
Sources/EpoxyLayoutGroups/Constraints/VGroupConstraints.swift
Sources/EpoxyLayoutGroups/Groups/HGroup.swift
Sources/EpoxyLayoutGroups/Models/GroupItem.swift
Sources/EpoxyLayoutGroups/Models/HGroupItem.swift
Sources/EpoxyLayoutGroups/Models/StaticGroupItem.swift
Sources/EpoxyLayoutGroups/Models/VGroupItem.swift
Sources/EpoxyLayoutGroups/Providers/AccessibilityAlignmentProviding.swift
Sources/EpoxyLayoutGroups/Providers/GroupItemsProviding.swift
Sources/EpoxyLayoutGroups/Providers/HorizontalAlignmentProviding.swift
Sources/EpoxyLayoutGroups/Providers/MakeConstrainableProviding.swift
Sources/EpoxyLayoutGroups/Providers/PaddingProviding.swift
Sources/EpoxyLayoutGroups/Providers/ReflowsForAccessibilityTypeSizeProviding.swift
Sources/EpoxyLayoutGroups/Providers/VerticalAlignmentProviding.swift
Tests/EpoxyTests/LayoutGroupsTests/ConstrainableContainerSpec.swift

This fixes an issue where VGroupConstraints in an accessibility layout would not respect the provided accessibility group alignment value because `AccessibilityAlignmentProviding` was non-optional. This change makes that property optional to match the other alignment values, and fixes the issue by using the group alignment when an individual `accessibilityAlignment` value is not provided.
As part of this I updated ConstrainableContainer and StaticGroupItem to use the provider protocols instead of ConstrainableContainer to inherit values
@erichoracek

fix some issues with alignment values

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/CollectionViewConfiguration.swift

While we're here, we additionally update `CollectionViewConfiguration` to be a struct to make it easier to mutate an existing configuration.

Use collection view batch updates for all reloads by default

---

CHANGELOG.md
Sources/EpoxyPresentations/PresentationModel.swift

By retaining the entire `context` in the captured observer closure, we're implicitly capturing the `context.presenting` `UIViewController` for the duration of the transition until the `DismissalTransitionDidEndNotification` notification is fired.
If the `DismissalTransitionDidEndNotification` is never triggered, e.g. in the case of early deallocation following presentation, this could lead to the presenting view controller being retained indefinitely.

Break temporary retain cycle in system presentation style

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/Internal/CollectionViewData.swift

- noticed this assert was logging the `indexPath.section` instead of `indexPath.item`

Fixed incorrect OOB assert logging

---

CHANGELOG.md
Sources/EpoxyBars/BarInstaller/BarContainer.swift
Sources/EpoxyBars/BottomBarInstaller/BottomBarContainer.swift
Sources/EpoxyBars/TopBarInstaller/TopBarContainer.swift
Tests/EpoxyTests/BarsTests/BaseBarInstallerSpec.swift
Tests/EpoxyTests/BarsTests/SafeAreaWindow.swift

This PR adds an `insetMargins` property to `TopBarContainer` and `BottomBarContainer` that configures whether or not the container sets layout margins derived from the `safeAreaInsets` of its `viewController`.

[EpoxyBars] Add `insetMargins` property to `TopBarContainer` and `BottomBarContainer`

---

CHANGELOG.md
Example/EpoxyExample/ViewControllers/LayoutGroups/ComplexDeclarativeViewController.swift
Sources/EpoxyLayoutGroups/Extensions/StyledView+GroupItem.swift
Sources/EpoxyLayoutGroups/Models/GroupItem.swift
Tests/EpoxyTests/LayoutGroupsTests/GroupItemSpec.swift
Tests/EpoxyTests/LayoutGroupsTests/TestHelpers.swift

[EpoxyLayoutGroups] fix diffIdentifier with mismatched styles

---

Example/EpoxyExample/ViewControllers/TextFieldViewController.swift
Example/EpoxyExample/Views/TextFieldRow.swift

We should have the source of truth for the input text string property in the view controller to make it more clear how text input should work with Epoxy.

[EpoxyCollectionView] Clarify text input example

---

CHANGELOG.md
Sources/EpoxyCollectionView/Models/SectionModel/SectionModel.swift
Sources/EpoxyCollectionView/ViewControllers/CollectionViewController.swift

As-is, the existing initializer makes it too easy to have sections that aren't possible to distinguish from one another, resulting in a runtime warning.

Make SectionModel data ID required

---

CHANGELOG.md
Example/EpoxyExample/ViewControllers/TextFieldViewController.swift
Sources/EpoxyBars/BarInstaller/BarInstaller.swift
Sources/EpoxyBars/BarInstaller/BarInstallerConfiguration.swift
Sources/EpoxyBars/BarInstaller/BarStackView.swift
Sources/EpoxyBars/BottomBarInstaller/BottomBarInstaller.swift
Sources/EpoxyBars/Keyboard/InputAccessoryBarStackView.swift
Sources/EpoxyBars/TopBarInstaller/TopBarInstaller.swift
Tests/EpoxyTests/BarsTests/BaseBarInstallerSpec.swift
Tests/EpoxyTests/BarsTests/BottomBarInstallerSpec.swift
Tests/EpoxyTests/BarsTests/TopBarInstallerSpec.swift
Tests/EpoxyTests/CollectionViewTests/CollectionViewSpec.swift
Tests/EpoxyTests/CollectionViewTests/FlowLayoutTests.swift

- Adds a new `BarInstallerConfiguration` type to allow both global and per-instance configuration of bar installers.
- Adds an `applyBars` closure to `BarInstallerConfiguration` to allow consumers to configure _when_ bars are applied to the underlying `BarContainer` by a bar installer.

[EpoxyBars] Support global and per instance bar installer configuration

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/Internal/CollectionViewScrollToItemHelper.swift

When we're scrolling to the item we should calculate the visible bounds using the `adjustedContentInset`. If we don't do this, the returned target origin is incorrect as it doesn't account for the safe area or content insets.

[EpoxyCollectionView] Fix animated scroll bounds checking

---

CHANGELOG.md
Sources/EpoxyLayoutGroups/Views/HGroupView.swift
Sources/EpoxyLayoutGroups/Views/VGroupView.swift

This PR lowers the bottom constraint priority on VGroupView and HGroupView's internal groups. The reason we do this is to allow the VGroupView to grow larger than the internal VGroup it contains. This is how UIStackView works as well where the content within the stack can be shorter than the size of the stack itself and results in much nicer looking layouts.

Lower bottom constraint priority for VGroupView and HGroupView

---

CHANGELOG.md
Sources/EpoxyBars/BottomBarInstaller/BottomBarContainer.swift
Sources/EpoxyBars/BottomBarInstaller/BottomBarInstaller.swift
Sources/EpoxyBars/TopBarInstaller/TopBarContainer.swift
Sources/EpoxyBars/TopBarInstaller/TopBarInstaller.swift
Tests/EpoxyTests/BarsTests/BottomBarInstallerSpec.swift
Tests/EpoxyTests/BarsTests/TopBarInstallerSpec.swift

This PR gives `BottomBarContainer` a `weak` reference to its `BottomBarInstaller`. This lets us access the `BottomBarInstaller` from extensions that add behavior to the `BottomBarContainer`.

Give BottomBarContainer a weak reference to its BottomBarInstaller

---

CHANGELOG.md
Sources/EpoxyBars/Keyboard/KeyboardPositionWatcher.swift

Fixes a bug in the `KeyboardPositionWatcher` that would consider an even slightly offscreen view as having a keyboard overlap when the keyboard is dismissed, resulting in incorrect keyboard offsets.

Fix KeyboardPositionWatcher dismissal logic with offscreen views

---

CHANGELOG.md
Sources/EpoxyCore/SwiftUI/EpoxySwiftUIHostingView.swift
Sources/EpoxyCore/SwiftUI/EpoxySwiftUIIntrinsicContentSizeInvalidator.swift

This change allows for transaction animations if state is mutated synchronously and allows SwiftUI components within epoxy to request size invalidation.

Allow SwiftUI transactions and size invalidation

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/CollectionView.swift
Sources/EpoxyCollectionView/CollectionView/Delegates/CollectionViewReorderingDelegate.swift

Add a support to check whether the destination is expected when drag and drop an item. 
If the new added method return `false`, it indicates that the destination item will be pinned and cannot be dropped an item.
It is implemented by leveraging `UICollectionViewDelegate.collectionView(_:targetIndexPathForMoveFromItemAt:toProposedIndexPath:) -> IndexPath`. This delegate method was deprecated in iOS 15, but I didn't implement the modern method due to this repo is still deployed in iOS 14+.

Added a method to `CollectionViewReorderingDelegate` to check the reordering destination is expected.

---

CHANGELOG.md
Sources/EpoxyCore/SwiftUI/EpoxySwiftUIHostingController.swift
Sources/EpoxyCore/SwiftUI/EpoxySwiftUIHostingView.swift

As of iOS 15.2, `UIHostingController` now renders updated content asynchronously, and as such this view will get sized incorrectly with the previous content when reused unless we invoke this semi-private API. We couldn't find any other method to get the view to resize synchronously after updating `rootView`, but hopefully this will become a public API soon so we can remove this call.
While we're here, and since SwiftUI has forced our hand to use semi-private APIs, we now migrate to using the `_disableSafeArea` API directly in the `EpoxySwiftUIHostingController`.
https://user-images.githubusercontent.com/438313/151228722-a9d995bd-f6e0-431e-9e1b-77df40be3905.mp4
https://user-images.githubusercontent.com/438313/151228745-57d8933c-6c33-4fa5-9700-1b276a7400a6.mp4
*How did you verify that this …

[SwiftUI] Fix reused UIHostingController sizing

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/Internal/CollectionViewScrollToItemHelper.swift

Fix crash in preferredFrameRateRanges on 15.0 devices

---

CHANGELOG.md
Sources/EpoxyCollectionView/ViewControllers/CollectionViewController.swift

This adds the ability to initialize a `CollectionViewController` with a `CollectionViewConfiguration`. Without this change, if a developer wants to provide a custom configuration in a non-global way, they wouldn't be able to use `CollectionViewController`, and instead would need to work with `CollectionView` directly. 

Add CV configuration options to CVVC

---

CHANGELOG.md
Sources/EpoxyCore/SwiftUI/EpoxyableView+SwiftUIView.swift
Sources/EpoxyCore/SwiftUI/LayoutUtilities/SwiftUIMeasurementContainer.swift
Sources/EpoxyCore/SwiftUI/LayoutUtilities/SwiftUISizingContainer.swift

We want to additionally support a `UIView` that's intrinsically sized when hosted within a SwiftUI `View`, rather than expanding to fill its parent's offered bounds which is what the current behavior supports.
While we're here, we also rework the way that we compute sizes to no longer require a `DispatchQueue.main.async` by switching to a `ObservableObject` in the sizing context.

[SwiftUI] Support more sizing behaviors in measurement container

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/CollectionView.swift
Sources/EpoxyCollectionView/CollectionView/CollectionViewConfiguration.swift
Sources/EpoxyCollectionView/CollectionView/ReusableViews/CollectionViewCell.swift

This PR attempts to workaround a layout recursion crash that only happens on iOS 15. Although the root cause of this crash is likely a component with ambiguous Auto Layout constraints, finding the component(s) with this bug can be very difficult (especially considering Xcode can't always detect when a layout is ambiguous).
To work around this crash / product-code bug, I've added some code to make it so that cells stop their sizing attempts after 5 tries. Why 5? Well, some components need 2 passes due to double-layout-pass labels being used. 3 seemed too risky / close to 2. 10 seems like too may attempts. How about half that? Sure, 5 it is 🌝 Open to suggestions 😛 
My plan is to put this change behind a feature flag in Airbnb code.
*How did you verify that this change accomplished what you …

Implement a workaround for the iOS 15 layout recursion crash

---

CHANGELOG.md
Sources/EpoxyCore/SwiftUI/EpoxyableView+SwiftUIView.swift
Sources/EpoxyCore/SwiftUI/LayoutUtilities/SwiftUIMeasurementContainer.swift
Sources/EpoxyCore/SwiftUI/LayoutUtilities/SwiftUISizingContainer.swift

Allow passing in a `SwiftUISizingStorage` `ObservedObject` since there are configurations where `StateObject`s are deallocated when offscreen (e.g. deeply nested views within a `LazyVStack`), and hoisting the sizing storage to the top-level content of the `ForEach` can mitigate this issue.
While we're here we also allow passing through the estimate and the measurement strategy all within a single `SwiftUISizingContainerConfiguration`, rather than specifying them separately.

[SwiftUI] Improve sizing configurability of SwiftUI-hosted UIViews

---

CHANGELOG.md
Sources/EpoxyCore/SwiftUI/LayoutUtilities/SwiftUIMeasurementContainer.swift
Sources/EpoxyCore/SwiftUI/LayoutUtilities/SwiftUISizingContainer.swift

Gracefully support cases where a `SwiftUIMeasurementContainer` with an `intrinsicSize` `SwiftUIMeasurementContainerStrategy` has an intrinsic size that exceeds the proposed size by compressing rather than overflowing, which could result in broken layouts.

[SwiftUI] Gracefully handle intrinsic sizes larger than available space

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/CollectionView.swift
Sources/EpoxyCollectionView/CollectionView/CollectionViewConfiguration.swift
Sources/EpoxyCollectionView/CollectionView/ReusableViews/CollectionViewCell.swift

This PR adds better layout recursion logging detection. The previous attempt had a few problems:
- Rotation / view width changes could incorrectly trigger the layout recursion detection
- Text input rows that increase in height as text is typed could incorrectly trigger the layout recursion detection
This PR makes a few improvements:
- Rather than try to prevent the crash, this PR simply logs (which should be "safer" / not cause other regressions like the last fix attempt did)
- Increase the sizing-attempt threshold to 50 attempts in less than 2 seconds
- Log the full history of sizing attempts
I tested this in the example project and confirmed the logging works as expected:
```
Layout recursion detected. View: <_TtGC12EpoxyExample13CardContainerC9EpoxyBars12BarStackView_: 0x7f8d8704b8f0; …
```

Add better layout recursion detection logging

---

Sources/EpoxyCollectionView/CollectionView/ReusableViews/CollectionViewCell.swift

Addressing feedback from previous PR https://github.com/airbnb/epoxy-ios/pull/88#discussion_r818333581
This adds VC logging so we have a better idea of which component is the problematic one when we detect layout recursion.

Also print parent view controller for layout recursion logging

---

CHANGELOG.md
Example/EpoxyExample/ViewControllers/SwiftUI/EpoxyInSwiftUIViewController.swift
Sources/EpoxyCore/SwiftUI/EpoxyableView+SwiftUIView.swift
Sources/EpoxyCore/SwiftUI/LayoutUtilities/SwiftUISizingContainer.swift
Sources/EpoxyCore/SwiftUI/UIView+SwiftUIView.swift
Sources/EpoxyCore/SwiftUI/UIViewConfiguringSwiftUIView.swift

- Added a static `swiftUIView(…)` method to `UIView` for hosting UIKit views that aren't
`EpoxyableView`s while still leveraging the layout helpers.
- Added support for calling `configure { _ in }` on the SwiftUI `View` resulting from a
`swiftUIView(…)` invocation to perform additional configuration of the `UIView` instance.

[SwiftUI] Add UIView swiftUIView helpers and support additional configuration closures

---

Sources/EpoxyCore/SwiftUI/EpoxyableView+SwiftUIView.swift
Sources/EpoxyCore/SwiftUI/LayoutUtilities/SwiftUIMeasurementContainer.swift
Sources/EpoxyCore/SwiftUI/LayoutUtilities/SwiftUISizingContainer.swift
Sources/EpoxyCore/SwiftUI/UIView+SwiftUIView.swift

In both of these cases, we don't need an estimate.

[SwiftUI] Don't use estimate sizes in the case of boundsSize or intrinsicSize UIViews

---

Sources/EpoxyCollectionView/CollectionView/ReusableViews/CollectionViewCell.swift

The previous thresholds (50 layout attempts in 2s) were resulting in virtually no logging events. This tweaks the thresholds so hopefully we can detect these layout loops.

Tweak thresholds for layout recursion detection

---

CHANGELOG.md
Sources/EpoxyLayoutGroups/Views/HGroupView.swift
Sources/EpoxyLayoutGroups/Views/VGroupView.swift

Update HGroupView and VGroupView to have insetsLayoutMarginsFromSafeArea = false by default

Update HGroupView and VGroupView to have insetsLayoutMarginsFromSafeArea = false by default

---

.spi.yml
Epoxy.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift

Following the steps here https://blog.swiftpackageindex.com/posts/auto-generating-auto-hosting-and-auto-updating-docc-documentation/

Add support for generating docc docuemntation on Swift Package Index

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/CollectionView.swift
Sources/EpoxyCollectionView/CollectionView/ReusableViews/CollectionViewCell.swift

I went through some old radars that I filed to see if any had been fixed - this one has been for iOS 14+.
I also removed the layout recursion detection since we have a better method (this one never really worked properly).

Remove and gate old workarounds by iOS version

---

Sources/EpoxyBars/BarModel/EpoxyableView+BarModel.swift
Sources/EpoxyCollectionView/Models/ItemModel/EpoxyableView+ItemModel.swift
Sources/EpoxyCollectionView/Models/SupplementaryItemModel/EpoxyableView+SupplementaryItemModel.swift
Sources/EpoxyLayoutGroups/Extensions/EpoxyableView+GroupItem.swift

We can't write `StyledView where Self: EpoxyableView` since that implies two `StyledView` conformances as `EpoxyableView` is defined as:
```swift 
typealias EpoxyableView = StyledView & ContentConfigurableView & BehaviorsConfigurableView
```

Fix redundant constraints identified Xcode 14

---

Epoxy.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift

The instructions were updated here https://blog.swiftpackageindex.com/posts/auto-generating-auto-hosting-and-auto-updating-docc-documentation/

Remove extra docc package dep, as this isn't required

---

CHANGELOG.md
Example/EpoxyExample.xcodeproj/project.pbxproj
Example/EpoxyExample/Data/Example.swift
Example/EpoxyExample/ViewControllers/MainViewController.swift
Example/EpoxyExample/ViewControllers/SwiftUI/SwiftUIInEpoxyResizingViewController.swift
Sources/EpoxyCore/SwiftUI/EpoxySwiftUIHostingView.swift

We need to invalidate the layout to get the the enclosing UICollectionView to allow the cell to resize.
Additionally adds an example to demonstrate this behavior.
https://user-images.githubusercontent.com/438313/177396250-705627bc-2eac-49ec-b82e-58f09fa57925.mp4

[SwiftUI] Fix size invalidation in a UICollectionView

---

CHANGELOG.md
Sources/EpoxyCore/Logging/EpoxyLogger.swift

In the same style as https://github.com/airbnb/lottie-ios/pull/1665, fixes an issue where `EpoxyLogger.shared.assertionFailure` and `EpoxyLogger.shared.assert` would unexpectedly crash in release builds.

Fix issue where EpoxyLogger asserts would unexpectedly crash in release builds

---

CHANGELOG.md
Sources/EpoxyCore/SwiftUI/EpoxyableView+SwiftUIView.swift
Sources/EpoxyCore/SwiftUI/LayoutUtilities/SwiftUIMeasurementContainer.swift
Sources/EpoxyCore/SwiftUI/UIView+SwiftUIView.swift

Adds a new `.automatic` sizing behavior for SwiftUI views embedded in Epoxy where the container makes a best effort to correctly choose the measurement strategy of the view based on a number of heuristics:
- The `UIView` will be given its intrinsic width and/or height when measurement in that dimension produces a positive value, while zero/negative values will result in that dimension receiving the available space proposed by the parent.
- If the view contains `UILabel` subviews that require a double layout pass as determined by a `preferredMaxLayoutWidth` that's greater than zero after a layout, then the view will default to `intrinsicHeightProposedWidth` to allow the labels to wrap.
*All …

[SwiftUI] Add automatic sizing option for UIKit in SwiftUI

---

CHANGELOG.md
Sources/EpoxyCore/SwiftUI/LayoutUtilities/SwiftUIMeasurementContainer.swift

- We only want to switch to `intrinsicHeightProposedWidth` when the view has a non-zero intrinsic width _and_ has double layout pass subviews, otherwise we can errantly switch to `intrinsicHeightProposedWidth` just due to the presence of a `UILabel` subview that isn't directly or indirectly constrained to the edges of the view. This happened with our video player.
- We also want to gracefully handle views with intrinsic sizes that are smaller than 1

[SwiftUI] Improve automatic sizing heuristic

---

CHANGELOG.md
Sources/EpoxyLayoutGroups/Models/HGroupItem.swift
Sources/EpoxyLayoutGroups/Models/VGroupItem.swift

This fixes https://github.com/airbnb/epoxy-ios/issues/56

Update HGroupItem and VGroupItem to use init(style:)

---

Epoxy.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Rakefile

This PR adds a workaround for issue where our dependency on the [airbnb/swift repo](https://github.com/airbnb/swift) causes Xcode to spin indefinitely at 100% CPU load. As discussed in https://github.com/airbnb/swift/pull/183 this is caused by the remote binary dependencies that package uses.
As a workaround, we can remove that dependency from our `Package.swift`. When running `bundle exec rake format:swift` / `bundle exec rake lint:swift`, we can temporarily add the dependency, run the linter/formatter, and then remove the dependency.

Add workaround for issue where airbnb/swift dependency causes Xcode to spin indefinitely at 100% CPU load

---

CHANGELOG.md
Sources/EpoxyCore/SwiftUI/LayoutUtilities/SwiftUIMeasurementContainer.swift

Improved sizing of intrinsically sized UIViews in SwiftUI with no intrinsic metric size proposals.
As-is, this results in some intrinsically sized views to be compressed to zero size height in certain cases on iOS 16 Beta 5.

[SwiftUI] Improve intrinsic sizing behaviors

---

CHANGELOG.md
Sources/EpoxyCore/SwiftUI/LayoutUtilities/SwiftUIMeasurementContainer.swift

Add extra logic for proposed sizes that match previous intrinsic size.

[SwiftUI] Fix bug that could prevent size changes

---

CHANGELOG.md
Example/EpoxyExample/ViewControllers/SwiftUI/EpoxyInSwiftUIViewController.swift
Sources/EpoxyCore/SwiftUI/EpoxyableView+SwiftUIView.swift
Sources/EpoxyCore/SwiftUI/LayoutUtilities/MeasuringUIViewRepresentable.swift
Sources/EpoxyCore/SwiftUI/LayoutUtilities/SwiftUIMeasurementContainer.swift
Sources/EpoxyCore/SwiftUI/SwiftUIUIView.swift
Sources/EpoxyCore/SwiftUI/UIView+SwiftUIView.swift
Sources/EpoxyCore/SwiftUI/UIViewConfiguringSwiftUIView.swift

We can remove all of the `EpoxyableView` flavors of `MeasuringUIViewRepresentable` in favor of a single shared `SwiftUIUIView` that supports a generic `Storage`. This has the added benefit of fixing some crashes we were seeing with Xcode previews.

[SwiftUI] Simplify UIKit in SwiftUI briding

---

.github/workflows/main.yml
CHANGELOG.md
ConfigurePodspec.rb
Package.swift
Tests/EpoxyTests/NavigationControllerTests/NavigationQueueSpec.swift

We use a new build matrix that covers Swift 5.5, 5.6, and 5.7

Drop Swift 5.4, update CI workflows to run on latest macos

---

CHANGELOG.md
Sources/EpoxyBars/BottomBarInstaller/BottomBarInstaller.swift

This is used to disable bottom bar keyboard avoidance in a case where the keyboard is avoided at a higher level, e.g. a `UIPresentationController` subclass.

[EpoxyBars] Add escape hatch to disable bottom bar keyboard avoidance

---

CHANGELOG.md
Sources/EpoxyCollectionView/Models/SupplementaryItemModel/AnySupplementaryItemModel.swift
Sources/EpoxyCollectionView/Models/SupplementaryItemModel/SupplementaryItemModel.swift
Sources/EpoxyCollectionView/Models/SupplementaryItemModel/SupplementaryItemModeling.swift

This add the equivalent API to the `ItemModeling` `configuredView(traitCollection)` method which IIUC was just an oversight when we implemented `SupplementaryItem`s.
https://github.com/airbnb/epoxy-ios/blob/42d2ad2d0f7bc78594ea5ab1534c02a2fe257601/Sources/EpoxyCollectionView/Models/ItemModel/ItemModeling.swift#L50

Add configuredView API to SupplementaryItemModeling

---

CHANGELOG.md
Sources/EpoxyNavigationController/NavigationModel.swift

A testing scenario at Airbnb requires the NavigationModel remove() func to be made public.
The scenario consists of simulating a backwards navigation in a test that does not have the entire view hierarchy built.
@bachand and @erichoracek FYI.

Making remove() method public in NavigationModel struct.

---

CHANGELOG.md
Sources/EpoxyNavigationController/NavigationModel.swift

Following up on #130:
We are also confident that we'll need to make handleDidRemove() public in that test scenario as well.
The scenario consists of simulating a backwards navigation in a test that does not have the entire view hierarchy built.
@bachand and @erichoracek FYI.

Making handleDidRemove() method public in NavigationModel struct.

---

Epoxy.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Rakefile
Sources/EpoxyNavigationController/NavigationModel.swift
Sources/EpoxyPresentations/PresentationModel.swift

This reverts #122.
Additionally runs the linter most recent linter and formatter.

Revert "Add workaround for issue where airbnb/swift dependency causes Xcode to spin indefinitely at 100% CPU load"

---

CHANGELOG.md
Sources/EpoxyBars/BarInstaller/UIScrollView+ContentOffset.swift
Sources/EpoxyBars/BarInstaller/UIView+HasHierarchy3DTransform.swift
Sources/EpoxyBars/BarInstaller/UIViewController+OriginalSafeAreaInsets.swift
Sources/EpoxyBars/BottomBarInstaller/BottomBarContainer.swift
Sources/EpoxyBars/TopBarInstaller/TopBarContainer.swift

If any view in the hierarchy has a 3D transform, it's not valid to apply the insets as they may be incorrect; we should wait until there is no transform to so do.

[EpoxyBars] Don't apply insets when hierarchy has a 3d transform

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/CollectionViewConfiguration.swift
Sources/EpoxyCollectionView/CollectionView/ReusableViews/CollectionViewCell.swift

- pass initial size to `CollectionViewCell`'s content view
- one of our Airbnb engineers noticed an issue where a SwiftUI view was laying out and loading images with an initial incorrect size, (72, 67) instead of the expected (320, 160)
- after tracing the code, I was seeing that an initial SwiftUI layout pass was occurring before the cell's content view received it's initial size

Pass Initial Size To CollectionViewCell ContentView

---

Sources/EpoxyBars/BarInstaller/BarContainer.swift
Sources/EpoxyBars/BottomBarInstaller/BottomBarContainer.swift
Sources/EpoxyBars/TopBarInstaller/TopBarContainer.swift

We can improve this logic by avoiding applying the inset with a hierarchy scale when it is less than the current inset; this fixes issues where new view controllers that were added to a scaled view don't receive their initial insets.

[EpoxyBars] Improve bar safe area logic

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/CollectionView.swift
Sources/EpoxyCollectionView/CollectionView/Internal/CollectionViewData.swift
Sources/EpoxyCollectionView/CollectionView/Internal/CollectionViewDataSource.swift
Sources/EpoxyCollectionView/CollectionView/ReusableViews/CollectionViewCell.swift
Tests/EpoxyTests/CollectionViewTests/CollectionViewSpec.swift

- fixes an issue discovered in the Airbnb app where while during a collection view update, the collection view will provide a didEndDisplay item callback for a cell that is only in the new data, this would cause a runtime assertion and incorrect view callbacks from being propagated

Fix Incorrect Item/Cell FoundDuring WillDisplay and DidEndDisplaying Callbacks

---

Sources/EpoxyCollectionView/CollectionView/CollectionView.swift
Sources/EpoxyCollectionView/CollectionView/Internal/CollectionViewData.swift
Sources/EpoxyCollectionView/CollectionView/Internal/CollectionViewDataSource.swift
Sources/EpoxyCollectionView/CollectionView/ItemPath.swift
Sources/EpoxyCollectionView/CollectionView/ItemSectionPath.swift
Sources/EpoxyCollectionView/CollectionView/ReusableViews/CollectionViewReusableView.swift
Sources/EpoxyCollectionView/CollectionView/SupplementaryItemPath.swift
Tests/EpoxyTests/CollectionViewTests/CollectionViewSpec.swift

- same fix as https://github.com/airbnb/epoxy-ios/pull/146 but for supplementary views

Fix Incorrect Supplementary Item Found During WillDisplay and DidEndDisplaying Callbacks

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/CollectionView.swift
Sources/EpoxyCollectionView/CollectionView/ReusableViews/CollectionViewCell.swift
Sources/EpoxyCollectionView/CollectionView/ReusableViews/Internal/CollectionViewCellAccessibilityDelegate.swift

- noticed this code can now be remove since it only worked for UITableView

Removed unused accessibility delegate

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/CollectionView.swift

- Uses the new functions [added here ](https://github.com/airbnb/epoxy-ios/pull/146)to avoid assertions when accessing visibility metadata during a batch update
- Added caching

Fix CollectionViewVisibilityMetadata Assertions and Cache

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/CollectionView.swift
Sources/EpoxyCollectionView/CollectionView/CollectionViewConfiguration.swift
Sources/EpoxyCollectionView/CollectionView/ReusableViews/CollectionViewCell.swift
Sources/EpoxyCollectionView/CollectionView/ReusableViews/CollectionViewReusableView.swift
Sources/EpoxyCollectionView/Models/ItemModel/SwiftUI.View+ItemModel.swift
Sources/EpoxyCore/SwiftUI/EpoxySwiftUIHostingView.swift

- an updated version of this PR using a collection view configuration flag https://github.com/airbnb/epoxy-ios/pull/152

[SwiftUI] Adds forcesEarlySwiftUIRendering flag to fix SwiftUI Cell Sizing

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/CollectionView.swift
Sources/EpoxyCollectionView/CollectionView/CollectionViewConfiguration.swift
Sources/EpoxyCollectionView/CollectionView/ReusableViews/CollectionViewCell.swift
Sources/EpoxyCollectionView/CollectionView/ReusableViews/CollectionViewReusableView.swift
Sources/EpoxyCore/SwiftUI/EpoxySwiftUIHostingView.swift

- removes this flag and updates the false given we've been testing this in the Airbnb app for a few weeks with no issues

Remove forcesEarlySwiftUIRendering flag and implementation

---

CHANGELOG.md
Sources/EpoxyCore/SwiftUI/EpoxySwiftUIHostingView.swift

Pin hosting controller to the top of the layout margin guide to ensure that a SwiftUI View used as `BarModel` is rendered below the top or bottom edge of the safe area.
|Before|After|
|---|---|
|![image (4)](https://github.com/airbnb/epoxy-ios/assets/20710815/678c2066-278c-45c4-8a0f-43380ca7209d)|![image (5)](https://github.com/airbnb/epoxy-ios/assets/20710815/49cca7ed-a6e9-4b35-be13-60ec7324d119)|

Pin hosting controller to the top of the layout margin guide

---

Sources/EpoxyCore/SwiftUI/EpoxySwiftUIHostingView.swift

Fixes an issue where the hosting view updates its safe area insets while being using inside a scrollview causing a broken layout

Fix EpoxySwiftUIHostingView updates safe area insets

---

CHANGELOG.md
Sources/EpoxyCore/SwiftUI/EpoxySwiftUIHostingView.swift

Revert https://github.com/airbnb/epoxy-ios/pull/157 and https://github.com/airbnb/epoxy-ios/pull/159

[iOS] Revert epoxy hosting view margin changes

---

CHANGELOG.md
Sources/EpoxyCollectionView/Models/ItemModel/AnyItemModel.swift
Sources/EpoxyCore/Model/Providers/ErasedContentProviding.swift

This PR changes `AnyItemModel` to implement the `ErasedContentProviding` protocol.
It also changes the `ErasedcontentProviding` protocol to use its type name instead of `Self` in the keys of its `EpoxyModelProperty` properties `contentProperty` and `isContentEqualProperty `.
We found this gap through a test failure that wasn't able to find a SwiftUI View used to build items of a `SectionModel`.
The reason for that is that these SwiftUI Views were placed in the `SectionModel` as `AnyItemModel` instances created from the call to `eraseToAnyItemModel()` method in the `ItemModeling` protocol:
```swift
extension AnyItemModel: ItemModeling {
public func eraseToAnyItemModel() -> AnyItemModel { self }
}
```
Our test framework has an implementation similar to the snippet below to find SwiftUI …

Making AnyItemModel implement ErasedContentProviding.

---

CHANGELOG.md
Example/EpoxyExample.xcodeproj/project.pbxproj
Example/EpoxyExample/Data/Example.swift
Example/EpoxyExample/ViewControllers/MainViewController.swift
Example/EpoxyExample/ViewControllers/SwiftUI/EpoxyInSwiftUISizingStrategiesViewController.swift
Sources/EpoxyCore/SwiftUI/LayoutUtilities/MeasuringViewRepresentable.swift
Sources/EpoxyCore/SwiftUI/LayoutUtilities/SwiftUIMeasurementContainer.swift

- fixes an issue when sizing bridged UILabel's to SwiftUI where the view would always take up the proposed size
- refactors sizing strategies for simplification and reducing unnecessary measurement
- added sizing strategies demo code

Refine UIKit to SwiftUI Measurement Strategies

---

CHANGELOG.md
Example/EpoxyExample/ViewControllers/SwiftUI/EpoxyInSwiftUISizingStrategiesViewController.swift
Sources/EpoxyCore/SwiftUI/LayoutUtilities/MeasuringViewRepresentable.swift
Sources/EpoxyCore/SwiftUI/LayoutUtilities/SwiftUIMeasurementContainer.swift

This reverts commit fb869c4930d88ea5f07c9970273c38c15b925f47.
- ran into some issues with this new approach in the Airbnb app due to unwanted side effects in the measurement container, the calls to sizeThatFits need to be purely functional (as much as possible)
- left sizing strategies demo in place

Partial Revert "Refine UIKit to SwiftUI Measurement Strategies (#162)"

---

Sources/EpoxyBars/BarModel/SwiftUI.View+BarModel.swift
Sources/EpoxyCore/SwiftUI/EpoxySwiftUIHostingView.swift

This reverts airbnb/epoxy-ios#161, which is not needed thanks to the existence of the `epoxyLayoutMargins` modifier.
```swift
// MARK: - View
extension View {
/// Applies the layout margins from the parent `EpoxySwiftUIHostingView` to this `View`, if there
/// are any.
///
/// Can be used to have a background in SwiftUI underlap the safe area within a bar installer, for
/// example.
///
/// These margins are propagated via the `EnvironmentValues.epoxyLayoutMargins`.
public func epoxyLayoutMargins() -> some View {
modifier(EpoxyLayoutMarginsPadding())
}
}
```
We can go back to always forcing `EpoxySwiftUIHostingView` to ignore safe area insets. Anyone who wants a bar to go into the safe area region can do so using `epoxyLayoutMargins`.
Note: We can't apply `epoxyLayoutMargins` …

Revert "Expose configuration to ignore EpoxySwiftUIHostingController safe area"

---

CHANGELOG.md
Sources/EpoxyBars/BarInstaller/BarStackView.swift

This works around a visionOS bug that causes SwiftUI views contained in hosting controllers to have broken interaction if their `zPosition`'s magnitude is too large. A safe workaround is to ensure that `zPosition` is always between -1 and 1, which provides ample precision for all of our needs.

Fix visionOS SwiftUI bar interaction

---

CHANGELOG.md
Sources/EpoxyBars/BarModel/SwiftUI.View+BarModel.swift
Sources/EpoxyCollectionView/Models/ItemModel/SwiftUI.View+ItemModel.swift
Sources/EpoxyCollectionView/Models/SupplementaryItemModel/SwiftUI.View+SupplementaryItemModel.swift
Sources/EpoxyCore/SwiftUI/EpoxySwiftUIHostingView.swift

This PR fixes the timing of layout and size invalidation when the layout margins change on an `EpoxySwiftUIHostingView`. For now, this only affects bar models, since those seem more likely to benefit from this change due to the the timing of layout margins being set during view controller transitions.
| Before | After |
| ---- | ---- |
| ![52516e8e-8764-49e3-afce-17951ae23f84](https://github.com/airbnb/epoxy-ios/assets/746571/6c7eadc0-ea03-4fa5-a594-d1e07c3e6b25) | ![39230544-32fa-43b9-8e2b-425417b69d28](https://github.com/airbnb/epoxy-ios/assets/746571/e66f40e5-7e4e-44d6-aa54-f5b59f9d8f9e) | 

Fix timing of layout margin layout invalidation for bars

---

.github/workflows/main.yml
CHANGELOG.md
Rakefile
Sources/EpoxyCore/SwiftUI/EpoxySwiftUIHostingController.swift
Sources/EpoxyCore/SwiftUI/EpoxySwiftUIHostingView.swift

This PR fixes an issue where an `EpoxySwiftUIHostingView` used as a bottom bar was being pushed above the keyboard when presented causing layout issues with the screen. [There doesn't seem to be a way to disable this from SwiftUI](https://steipete.com/posts/disabling-keyboard-avoidance-in-swiftui-uihostingcontroller/) (`.ignoresSafeArea(.keyboard)` doesn't work) so this uses dynamic subclassing to override the hosting controller's `keyboardWillShowWithNotification` method.

Add flag to disable `EpoxySwiftUIHostingController` keyboard avoidance

---

Example/EpoxyExample/ViewControllers/LayoutGroups/ComplexDeclarativeViewController.swift
Sources/EpoxyBars/BarInstaller/BarWrapperView.swift
Sources/EpoxyBars/BarModel/BarModel.swift
Sources/EpoxyCollectionView/Models/ItemModel/ItemModel.swift
Sources/EpoxyCollectionView/Models/SupplementaryItemModel/SupplementaryItemModel.swift
Sources/EpoxyCore/Diffing/Collection+Diff.swift
Sources/EpoxyCore/Model/Providers/WillDisplayProviding.swift
Sources/EpoxyLayoutGroups/Constrainable/Constrainable.swift
Sources/EpoxyLayoutGroups/Groups/HGroup.swift
Sources/EpoxyLayoutGroups/Models/GroupItem.swift
Sources/EpoxyLayoutGroups/Providers/AccessibilityAlignmentProviding.swift
Sources/EpoxyLayoutGroups/Providers/ReflowsForAccessibilityTypeSizeProviding.swift
Sources/EpoxyLayoutGroups/Types/LayoutGroupUpdateAnimation.swift
Sources/EpoxyNavigationController/NavigationQueue.swift
Tests/EpoxyTests/CoreTests/CollectionDiffSpec.swift
Tests/EpoxyTests/LayoutGroupsTests/HGroupSpec.swift
Tests/EpoxyTests/NavigationControllerTests/StubTransitionCoordinator.swift

Fix some typos

---

CHANGELOG.md
Sources/EpoxyCore/SwiftUI/EpoxySwiftUIHostingView.swift

Expose `forceLayout` in EpoxySwiftUIHostingView

Expose `forceLayout` in EpoxySwiftUIHostingView

---

CHANGELOG.md
Sources/EpoxyCollectionView/CollectionView/CollectionViewConfiguration.swift
Sources/EpoxyCollectionView/ViewControllers/CollectionViewController.swift

Adds support for respecting leading/trailing safe areas for landscape orientation

usesSafeAreaLayoutGuideLeadingTrailing
